### ISSUE TITLE
Bug: Test results in first step

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/using-github-actions-for-ci#11] opened 2019-09-27 09:20 UTC
In the first step, I am not sure what to expect from the tests; but, I see that the CI is failing or cancelled and I'm not sure how to proceed.

<img width="604" alt="Screen Shot 2019-09-27 at 11 19 44" src="https://user-images.githubusercontent.com/9906718/65758098-bd208300-e118-11e9-8c48-521c26f16faa.png">

**Comment by ntaranov** [comment] 2020-06-01 19:35
I too had impression that the bug might be caused by the workflow runner canceling 2 tests of 3 after first of them fails, so I updated my workflow template to only contain 1 Node.js version. The result is the same. The 'gate' check itself is likely broken. 

![image](https://user-images.githubusercontent.com/16212382/83446874-7a3c4b00-a41d-11ea-97e4-60ea216b1f97.png)

**Comment by mattdavis0351** [comment] 2020-06-09 02:29
Problem was solved and merged into master!  It was a combination of changing the course config as well as other changes to the starter workflow.  #43 and #41 combined have solved the issue.

**Closed by mattdavis0351** 2020-06-09 02:29 UTC
Labels: bug
